name: SBOM Analysis Workflow

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Type of scan (trivyfs, trivyimage, grypefs, grypeimage, syftfs, syftimage)'
        required: true
        default: 'grypefs'
      target:
        description: 'Scan target (applicable for image scans)'
        required: false
        default: ''

jobs:
  sbom_scan:
    uses: sbom.sh/sbom.sh-sbom@v1
    with:
      scan_type: ${{ github.event.inputs.scan_type }}
      target: ${{ github.event.inputs.target }}

