name: "Generate and Upload SBOM"

on: [push, pull_request, workflow_dispatch]

jobs:
  generate_sbom:
    runs-on: ubuntu-latest
    name: "SBOM Generation"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Generate SBOM
        uses: sbom-to-sbom-sh@v1
        with:
          scan_type: 'grypefs' # Or other supported types like 'trivyfs', 'syftfs', etc.
      
      - name: Output SBOM URL
        run: echo "The SBOM can be found at ${{ steps.sbom_generation.outputs.sbom_url }}"

